Repository We1l6/RollForHonor, pull requests merged in 2025-06, with the labels that each got.

#1 feat(init): Add project structure and .gitignore
  CMakeLists.txt
  cmake/AddGitSubmodule.cmake
  cmake/Sanitizers.cmake
  cmake/Warnings.cmake
  docs/.gitkeep
  external/.gitkeep
  resources/.gitkeep
  scripts/.gitkeep
  src/.gitkeep
  test/.gitkeep
Labels: enhancement, ci, infrastructure

#8 test: gitHub actions(doxygen)
  Doxyfile
  src/main.cpp
Labels: documentation, ci

#9 feat(test): add run tests on merge to develop
  .github/workflows/testOnDevelop.yml
  test/CMakeLists.txt
Labels: tests, ci

#12 feat: add userInterface and button classes
  .gitignore
  CMakeLists.txt
  src/CMakeLists.txt
  src/main.cpp
  src/userInterface/UIUtils.h
  src/userInterface/button/button.cpp
  src/userInterface/button/button.h
  src/userInterface/userInterface.cpp
  src/userInterface/userInterface.h
Labels: enhancement

#16 feat: add logger
  src/CMakeLists.txt
  src/loggerManager/loggerManager.cpp
  src/loggerManager/loggerManager.h
Labels: enhancement

#23 feat: add scrollBarr class, change ui code style
  src/CMakeLists.txt
  src/main.cpp
  src/userInterface/UIUtils/RectanglePro/RectanglePro.cpp
  src/userInterface/UIUtils/RectanglePro/RectanglePro.h
  src/userInterface/UIUtils/TextPro/TextPro.cpp
  src/userInterface/UIUtils/TextPro/TextPro.h
  src/userInterface/button/button.cpp
  src/userInterface/button/button.h
  src/userInterface/scrollBar/scrollBar.cpp
  src/userInterface/scrollBar/scrollBar.h
  src/userInterface/userInterface.cpp
  src/userInterface/userInterface.h
Labels: enhancement

#25 feat: add texture manager fn
  resources/.gitkeep
  resources/texture.jpg
  src/main.cpp
  src/resourceManager/resourceManager.cpp
  src/resourceManager/resourceManager.h
  src/textureManager/textureManager.cpp
  src/textureManager/textureManager.h
Labels: enhancement

#31 feat: add sceneManager, scene
  src/CMakeLists.txt
  src/main.cpp
  src/managers/sceneManager/sceneManager.cpp
  src/managers/sceneManager/sceneManager.h
  src/scenes/mainMenuScene/mainMenuScene.cpp
  src/scenes/mainMenuScene/mainMenuScene.h
  src/scenes/scene/scene.h
Labels: enhancement, infrastructure
